services:
  app:
    container_name: "danklyrics-web"
    build:
      context: .
    image: "danklyrics"
    restart: "always"
    ports:
      - "20420:8080"
    stdin_open: true
    env_file: .env.docker
