FROM golang:1.24-alpine AS build

WORKDIR /app
COPY . .

RUN go mod tidy && \
    go build -ldflags="-w -s" -o danklyrics-admin ./cmd/admin/main.go

FROM alpine:latest AS run

WORKDIR /app
COPY --from=build /app/danklyrics-admin .

EXPOSE 8082

CMD ["./danklyrics-admin"]
