services:
  danklyrics-web:
    container_name: "danklyrics-web"
    build:
      context: .
    restart: "always"
    ports:
      - "20420:8080"
    stdin_open: true
    env_file: .env.docker
    networks:
      - danklyricsnetwork

  danklyrics-api:
    container_name: "danklyrics-api"
    build:
      context: .
      dockerfile: Dockerfile.api
    restart: "always"
    ports:
      - "20421:8081"
    stdin_open: true
    env_file: .env.docker
    networks:
      - danklyricsnetwork

  danklyrics-admin:
    container_name: "danklyrics-admin"
    build:
      context: .
      dockerfile: Dockerfile.admin
    restart: "always"
    ports:
      - "20419:8082"
    stdin_open: true
    env_file: .env.docker
    networks:
      - danklyricsnetwork

networks:
  danklyricsnetwork: {}
